# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8yPrVjHvz3PDna_rzrUgGItaeXn_LKt
"""

a=input()
i=0
while((len(a)-1)>(i)):
    print(a[i],end=",")
    i=i+1
print(a[i])